name: "Build package"

on:
  push:
    branches:['main']

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:

    - name: "â¬‡ Checkout"
      uses: actions/checkout@v2

    - name: "ğŸ— Run CustoPiZer"
      run: |
        sudo apt update \
        sudo apt upgrade \
        echo "this is a test"


